### ISSUE TITLE
Packages installed to `/opt` unavailable at runtime

### ISSUE THREAD

**Issue by sabberworm** [cloudfoundry/apt-buildpack#194]
> What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```json
{
  "name": "",
  "build": "",
  "support": "https://***REDACTED***",
  "version": 0,
  "description": "Cloud Foundry provided by ***REDACTED***",
  "authorization_endpoint": "https://***REDACTED***",
  "token_endpoint": "https://***REDACTED***",
  "min_cli_version": "6.51.0",
  "min_recommended_cli_version": "latest",
  "app_ssh_endpoint": "ssh.***REDACTED***",
  "app_ssh_host_key_fingerprint": "***REDACTED***",
  "app_ssh_oauth_client": "ssh-proxy",
  "doppler_logging_endpoint": "wss://***REDACTED***",
  "api_version": "2.218.0",
  "osbapi_version": "2.15",
  "routing_endpoint": "https://***REDACTED***",
  "user": "***REDACTED***"
}
```

```
cf version 8.7.8+515cf4e.2024-02-08
```

> What version of the buildpack you are using?

0.3.5

> If you were attempting to accomplish a task, what was it you were attempting to do?

I was trying to install google-chrome-stable, from https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.60-1_amd64.deb.

Manifest:
```yaml
---
applications:
    buildpacks:
      - apt_buildpack
      - nodejs_buildpack
```

apt.yml:
```yaml
---
truncatesources: true
cleancache: true
keys:
  # FIXME: Use the key from dl.google.com, once https://github.com/cloudfoundry/apt-buildpack/issues/163 is fixed
  # - https://dl.google.com/linux/linux_signing_key.pub
  - ***REDACTED***
repos:
  - deb [arch=amd64] https://***REDACTED***/ stable main
packages:
  - google-chrome-stable
```

> What did you expect to happen?

The installed binary is usable.

> What was the actual behavior?

The package gets installed but `/opt` is empty at runtime. `~/deps/0/bin/google-chrome-stable` and `~/deps/0/apt/usr/bin/google-chrome-stable` exist but are broken symlinks to `/opt/google/chrome/google-chrome`.

Maybe related to #25?
