### ISSUE TITLE
The method driver /usr/lib/apt/methods/https could not be found

### ISSUE THREAD

**Issue by JohannesRudolph** [cloudfoundry/apt-buildpack#9]
What version of the buildpack you are using?
develop

If you were attempting to accomplish a task, what was it you were attempting to do?

I tried to install the cf-cli using this `apt.yml`:
```yml
keys:
- https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key

repos:
- deb http://packages.cloudfoundry.org/debian stable main

packages:
- cf-cli
```

What did you expect to happen?

The package should install fine. 

What was the actual behavior?

I got a staging error:
```
   -----> Apt Buildpack version 0.1.1
   -----> Adding apt keys
   gpg: key 50C212B6: public key "CF CLI Team <cf-cli-eng@pivotal.io>" imported
   gpg: Total number processed: 1
   gpg:               imported: 1  (RSA: 1)
   -----> Adding apt repos
   -----> Updating apt cache
   E: The method driver /usr/lib/apt/methods/https could not be found.
          **ERROR** Failed to update apt cache: exit status 100
          Ign http://archive.ubuntu.com trusty InRelease

```

It does not matter if I use `http://packages.cloudfoundry.org/debian` or `https://packages.cloudfoundry.org/debian` in the apt.yml. 

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Suggested fix: **
The apt buildpack should pre-install the apt-transport-https package if it detects a http repository in  `apt.yml`. This should fix the installation error.
